### ISSUE TITLE
How do we push CLI commands to SONiC switches via REST?

### ISSUE THREAD

**Issue by asydney** [Azure/sonic-mgmt-framework#82]
Hi SONiC-RESTAPI folks,
                                        I was able to configure a virtual testbed of SONiC switches and below is just a snippet of some of the following commands:
"""
sonic> sudo config interface ip remove Ethernet16 10.0.0.8/31
sonic> sudo config interface ip add Ethernet16 10.10.1.2/31
sonic> sudo config interface ip add Loopback0 10.0.1.13/32
sonic> sudo vtysh
sonic> configure t
sonic> no router bgp 65100
sonic> router bgp 65021
sonic> bgp router-id 10.0.1.13
"""

Questions:
Can I push these configurations remotely via REST? 
    * If yes, can you kindly point to documentation on how? In particular, do I need to install rest specific containers as shown here https://github.com/Azure/sonic-restapi ? 
    * At the moment, I do see a "/usr/sbin/rest_server" process running and perhaps attached to port 443? So maybe all I do need is a REST client on the host to push the configs? If yes, can you point me to documentation setting up the client (Perhaps a "curl" example?)? 

Thanks,
-Syd

**Comment by ljyfree** [comment]
You could try _/usr/sbin/clish_start_ in mgmt-framework docker.

**Comment by asydney** [comment]
I hopped onto "mgmt-framework" docker container and "/usr/sbin/cli/clish_start" provides an interface to execute commands. However, it's not clear how it can be used remotely.

Let me clarify the original question... I would like to execute a command such as "show version" from a remote host, to a switch running SONiC: below is the topology that shows the connection between my remote_host system and the sonic switch: 

remote_host <-> sonic_switch

Below is an example of how this can be done using "curl" assuming our switch has management IP 192.168.1.5 and has a rest server listening on port 80 with the REST endpoint "comman-api":

remote_host> curl --insecure -u admin -H "Content-Type: application/json" -X POST -d '{"jsonrpc":"2.0", "method":"runCmds", "params":{ "version":1, "cmds":["show version"], "format":"json"}, "id":""}' http:///192.168.1.5:80/command-api | json_reformat

So how could I execute "show version" similarly for sonic switches?

**Comment by ljyfree** [comment]
All I know is that you could open SONiC REST API explorer on https://192.168.1.5/ui ,which were compiled from yang model.
As for "comman-api" , I have no clue.

**Comment by asydney** [comment]
Indeed.. I came across this same info from the URL below:

https://github.com/Azure/SONiC/blob/master/doc/mgmt/Management%20Framework.md#322415-api-documentation

When I click on a given definition (e.g. openconfig-interfaces.yaml), there are a list of REST endpoints and for example, when I click on "GET /openconfig-interfaces:interfaces", I"m provided with the "curl" command executed (e.g. curl -X GET "https://192.168.122.10/restconf/data/openconfig-interfaces:interfaces" -H "accept: application/yang-data+json"), the request URL and also the response. 

So I'm investigating a bit to determine if I can use this interface to perhaps convert the CLI commands to their REST equivalents.

**Comment by ljyfree** [comment]
I realize your request looks like “Docker to Host Comminication”,which was described in https://github.com/Azure/SONiC/blob/master/doc/mgmt/Docker%20to%20Host%20communication.md

**Comment by mayuresh82** [comment]
@ljyfree  i dont think you have any clue about what the OP is asking so please refrain from shit-posting

**Comment by ljyfree** [comment]
@mayuresh82 Thanks for your kind reminder,shit-posting judge.
